# name: DiT
# channels:
#   - pytorch
#   - nvidia
# dependencies:
#   - python >= 3.8
#   - pytorch >= 1.13
#   - torchvision
#   - pytorch-cuda=11.7
#   - pip:
#     - timm
#     - diffusers
#     - accelerate

# name: DiT
channels:
  - pytorch
  - nvidia
dependencies:
  - python >= 3.8
  - pip:
    - timm
    - diffusers
    - accelerate

# pytorch-fid
# pytorch-cuda=12.6
# pytorch >= 2.5?
# python 3.13.2 je pense